/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'raul' at '5/9/16 6:47 AM' with Gradle 2.12
 *
 * @author raul, @date 5/9/16 6:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
